#ifndef RAFGL_KEYS_H_INCLUDED
#define RAFGL_KEYS_H_INCLUDED

#include <GLFW/glfw3.h>

#define RAFGL_KEY_SPACE        GLFW_KEY_SPACE
#define RAFGL_KEY_ESCAPE       GLFW_KEY_ESCAPE
#define RAFGL_KEY_ENTER        GLFW_KEY_ENTER
#define RAFGL_KEY_TAB          GLFW_KEY_TAB
#define RAFGL_KEY_BACKSPACE    GLFW_KEY_BACKSPACE
#define RAFGL_KEY_LEFT         GLFW_KEY_LEFT
#define RAFGL_KEY_RIGHT        GLFW_KEY_RIGHT
#define RAFGL_KEY_UP           GLFW_KEY_UP
#define RAFGL_KEY_DOWN         GLFW_KEY_DOWN
#define RAFGL_KEY_LEFT_SHIFT   GLFW_KEY_LEFT_SHIFT
#define RAFGL_KEY_RIGHT_SHIFT  GLFW_KEY_RIGHT_SHIFT
#define RAFGL_KEY_LEFT_CONTROL GLFW_KEY_LEFT_CONTROL
#define RAFGL_KEY_RIGHT_CONTROL GLFW_KEY_RIGHT_CONTROL
#define RAFGL_KEY_LEFT_ALT     GLFW_KEY_LEFT_ALT
#define RAFGL_KEY_RIGHT_ALT    GLFW_KEY_RIGHT_ALT

#endif
